FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ChatBotWithOpenAI.csproj", "./"]
RUN dotnet restore "./ChatBotWithOpenAI.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ChatBotWithOpenAI.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "ChatBotWithOpenAI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChatBotWithOpenAI.dll"]